# Generated by Django 4.0.3 on 2022-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
